#!/usr/bin/env python3
"""
Generate text using a trained BDH model.

This script loads a saved checkpoint and generates text from a prompt.
"""

import torch
import bdh
import sys
import os

def load_checkpoint(checkpoint_path):
    """
    Load a checkpoint file and return model, config, and metadata.
    
    Args:
        checkpoint_path: Path to the checkpoint file (.pt)
        
    Returns:
        model: Loaded BDH model
        config: BDHConfig used for the model
        metadata: Dictionary with training info (step, loss, etc.)
    """
    print(f"Loading checkpoint from {checkpoint_path}...")
    
    # Load checkpoint (use CPU for loading, then move to device)
    # weights_only=False is needed because checkpoint contains custom BDHConfig object
    # This is safe since it's our own checkpoint file
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    
    # Extract config (if saved in checkpoint) or use default
    if 'config' in checkpoint:
        config = checkpoint['config']
        print(f"Loaded config from checkpoint")
    else:
        # Try to infer from checkpoint filename or use default
        config = bdh.BDHConfig()
        print(f"Using default config (config not found in checkpoint)")
    
    # Create model with the config
    print(f"Creating model: n_layer={config.n_layer}, n_embd={config.n_embd}, "
          f"mlp_mult={config.mlp_internal_dim_multiplier}")
    model = bdh.BDH(config)
    
    # Load model weights
    if 'model_state_dict' in checkpoint:
        model.load_state_dict(checkpoint['model_state_dict'])
        print("Model weights loaded successfully")
    else:
        # Assume the checkpoint IS the state_dict
        model.load_state_dict(checkpoint)
        print("Loaded checkpoint as state_dict")
    
    # Extract metadata
    metadata = {
        'step': checkpoint.get('step', 'unknown'),
        'loss': checkpoint.get('loss', 'unknown'),
        'epoch': checkpoint.get('epoch', 'unknown'),
    }
    
    return model, config, metadata

def generate_text(model, prompt_text, max_new_tokens=200, temperature=1.0, top_k=3, device="cpu"):
    """
    Generate text from a prompt using the model.
    
    Args:
        model: BDH model (should be in eval mode)
        prompt_text: Text prompt to start generation from
        max_new_tokens: Maximum number of new tokens to generate
        temperature: Sampling temperature (higher = more random)
        top_k: Only consider top-k most likely tokens
        device: Device to run generation on ("cpu", "mps", or "cuda")
        
    Returns:
        Generated text (prompt + generated continuation)
    """
    # Set model to evaluation mode
    model.eval()
    model = model.to(device)
    
    # Convert prompt to tensor
    prompt_bytes = bytearray(prompt_text, "utf-8")
    prompt_tensor = torch.tensor(prompt_bytes, dtype=torch.long, device=device).unsqueeze(0)
    
    print(f"\nPrompt: '{prompt_text}'")
    print(f"Generating {max_new_tokens} tokens...")
    print("-" * 60)
    
    # Generate
    with torch.no_grad():
        generated = model.generate(
            prompt_tensor,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_k=top_k,
        )
    
    # Decode generated bytes to text
    generated_bytes = bytes(generated.to(torch.uint8).to("cpu").squeeze(0))
    generated_text = generated_bytes.decode(errors="backslashreplace")
    
    return generated_text

def main():
    """Main function to load model and generate text."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate text using a trained BDH model")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default="bdh_checkpoint_step_100.pt",
        help="Path to checkpoint file (default: bdh_checkpoint_step_100.pt)"
    )
    parser.add_argument(
        "--prompt",
        type=str,
        default="To be or not to be",
        help="Text prompt to start generation from (default: 'To be or not to be')"
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=200,
        help="Maximum number of tokens to generate (default: 200)"
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=1.0,
        help="Sampling temperature - higher = more random (default: 1.0)"
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=3,
        help="Only consider top-k most likely tokens (default: 3)"
    )
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        choices=["auto", "cpu", "mps", "cuda"],
        help="Device to use (default: auto - detects best available)"
    )
    
    args = parser.parse_args()
    
    # Determine device
    if args.device == "auto":
        if torch.cuda.is_available():
            device = "cuda"
        elif torch.backends.mps.is_available():
            device = "mps"
        else:
            device = "cpu"
    else:
        device = args.device
    
    print(f"Using device: {device}")
    
    # Check if checkpoint exists
    if not os.path.exists(args.checkpoint):
        print(f"Error: Checkpoint file '{args.checkpoint}' not found!")
        print(f"Available checkpoint files:")
        for f in os.listdir("."):
            if f.endswith(".pt"):
                print(f"  - {f}")
        sys.exit(1)
    
    # Load model
    try:
        model, config, metadata = load_checkpoint(args.checkpoint)
        print(f"\nCheckpoint info:")
        print(f"  Step: {metadata['step']}")
        print(f"  Loss: {metadata['loss']}")
    except Exception as e:
        print(f"Error loading checkpoint: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    # Generate text
    try:
        generated = generate_text(
            model,
            args.prompt,
            max_new_tokens=args.max_tokens,
            temperature=args.temperature,
            top_k=args.top_k,
            device=device
        )
        
        print("\n" + "=" * 60)
        print("GENERATED TEXT:")
        print("=" * 60)
        print(generated)
        print("=" * 60)
        
    except Exception as e:
        print(f"Error during generation: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()